# Copyright (c) 2026 Hringbord
# SPDX-License-Identifier: MIT

# Enable deep sleep support (uncomment to activate)
# CONFIG_ZMK_SLEEP=y

# Lighting features
# CONFIG_ZMK_RGB_UNDERGLOW is not set
# CONFIG_ZMK_BACKLIGHT is not set
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y
CONFIG_ZMK_BEHAVIOR_LOCAL_IDS=y

